export const GET_STARTUPS = "GET_STARTUPS";
export const SET_LOADING = "SET_LOADING";
export const ADD_STARTUP = "ADD_STARTUP";
export const DELETE_STARTUP = "DELETE_STARTUP";
export const UPDATE_STARTUP = "UPDATE_STARTUP";
export const STARTUPS_ERROR = "STARTUPS_ERROR";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ADD_INVESTMENTS = "ADD_INVESTMENT";
export const ADD_KPI_NAMES = "ADD_KPI_NAME";
export const ADD_FINANCIAL = "ADD_FINANCIAL";

export const DELETE_KPI_NAME = "DELETE_KPI_NAME";
export const DELETE_INVESTMENT = "DELETE_INVESTMENT";
