# Generated by Django 3.0.4 on 2020-03-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('website', models.CharField(blank=True, max_length=100, unique=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('ownership', models.IntegerField(blank=True, null=True)),
                ('board', models.CharField(blank=True, max_length=30, null=True)),
                ('investment_1', models.IntegerField(blank=True, default=0)),
                ('investment_2', models.IntegerField(blank=True, default=0)),
                ('type_1', models.CharField(blank=True, max_length=30, null=True)),
                ('type_2', models.CharField(blank=True, max_length=30, null=True)),
                ('date_closed_1', models.DateTimeField(auto_now_add=True)),
                ('date_closed_2', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
