# Generated by Django 3.0.4 on 2020-03-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='date_closed_1',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='date_closed_2',
            field=models.DateField(auto_now_add=True),
        ),
    ]
