# Generated by Django 3.0.4 on 2020-03-25 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='startups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='startup',
            name='date_closed_1',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='date_closed_2',
            field=models.DateField(blank=True),
        ),
    ]
