# Generated by Django 3.0.4 on 2020-04-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financial',
            options={'ordering': ['-startDate']},
        ),
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-date']},
        ),
    ]
