# Generated by Django 3.0.4 on 2020-03-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='money',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='name_1',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
