# Generated by Django 3.0.4 on 2020-03-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_auto_20200327_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='name_1',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
