# Generated by Django 3.0.4 on 2020-03-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_auto_20200321_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='investment_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='investment_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
