# Generated by Django 3.0.4 on 2020-03-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_auto_20200322_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='investment_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='startup',
            name='investment_2',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
