# Generated by Django 3.0.4 on 2020-03-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0007_auto_20200324_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='runway',
            new_name='cash_balance',
        ),
    ]
