# Generated by Django 3.0.4 on 2020-03-24 23:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0008_auto_20200324_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='kpi_string',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), default=0, size=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='kpi_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None), default=1, size=500),
            preserve_default=False,
        ),
    ]
