# Generated by Django 3.0.4 on 2020-03-24 23:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0009_auto_20200324_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='kpi_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0), size=None), size=500),
        ),
    ]
