# Generated by Django 3.0.4 on 2020-03-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0010_auto_20200324_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='kpi_string',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='kpi_value',
        ),
    ]
