# Generated by Django 2.0.2 on 2020-02-13 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'financial_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('request_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.NullBooleanField()),
            ],
            options={
                'db_table': 'requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Startups',
            fields=[
                ('startup_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('logo_url', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('ownership', models.IntegerField(blank=True, null=True)),
                ('board', models.CharField(blank=True, max_length=30, null=True)),
                ('first_investment', models.IntegerField(blank=True, null=True)),
                ('second_investment', models.IntegerField(blank=True, null=True)),
                ('type_1', models.CharField(blank=True, max_length=30, null=True)),
                ('type_2', models.CharField(blank=True, max_length=30, null=True)),
                ('date_closed_1', models.DateTimeField()),
                ('date_closed_2', models.DateTimeField()),
            ],
            options={
                'db_table': 'startups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'team_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=355, unique=True)),
                ('created_on', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vcs',
            fields=[
                ('vc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('logo_url', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'vcs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VcsStartups',
            fields=[
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tracksy.Startups')),
            ],
            options={
                'db_table': 'vcs_startups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VcsUsers',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tracksy.Users')),
            ],
            options={
                'db_table': 'vcs_users',
                'managed': False,
            },
        ),
    ]
